# Site wide configuration
locale                   : "en-US"
encoding                 : UTF-8
title                    : "Home"
title_separator          : "-"
name                     : &name "Hudson"
description              : &description "Automation"
url                      : https://chudson121.github.io # overridden by _config-dev.yml during jekyll serve.
github:
   repo:  https://github.com/chudson121/chudson121.github.io
teaser                   : # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
# breadcrumbs            : false # true, false (default)
permalink: /blog/:year/:month/:day/:title