# use where a full URL is appropriate (e.g. RSS, OG tags)
url: HTTPS://chudson121.github.io
domain: chudson121.github.io
contact: chudson121@hotmail.com
contactPhone: 8134214342

# blog archive at /news
# paginate: 50
paginate_path: "blog/page:num"

#force Jekylle to show future posts immediatly
future: true

#permalink: /blog/:year/:month/:day/:title
markdown: kramdown

# Includes an icon in the footer for each user name you enter
footer-links:

theme: minima

